name: Entrega Contínua ECS

on:
  workflow_call:

jobs:
  
  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v6.2.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition Tarefa_API-Go --query taskDefinition > task-definition.json

    - name: Cópia do task-definition
      run: cp task-definition.json task-definition.json.old

    - name: Colocar um novo ID de imagem no task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Go
        image: marcelobezz07/api-go-dev:${{ github.run_number }}
        environment-variables: |
          DB_HOST=${{ secrets.DBHOST }}
          DB_USER=${{ secrets.DBUSER }}
          DB_PASSWORD=${{ secrets.DBPASSWORD }}
          DB_NAME=${{ secrets.DBNAME }}
          DB_PORT=${{ secrets.DBPORT }}
          PORT=8000

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: Servico_API-Go
        cluster: API-Go
        wait-for-service-stability: true

    - name: Requisição
      continue-on-error: true
      run: echo "REQUEST=0" >> $GITHUB_ENV ; sleep 30s ; wget LB-API-Go-1366897533.us-west-2.elb.amazonaws.com:8000/marcelo || echo "REQUEST=1" >> $GITHUB_ENV

    - name: Deploy Amazon ECS task definition old
      if: ${{ env.REQUEST != 0 }}
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: task-definition.json.old
        service: Servico_API-Go
        cluster: API-Go
        wait-for-service-stability: true